### ISSUE TITLE
Missing weapons and other errors

### ISSUE THREAD

**Issue by RylaiSlyfe** [asdfjackal/warframe-checklist#15]
Missing weapons:
*"Sigma & Octantis" through daily login
*"Zenith" also through daily login

Errors:
*Weapon "Grinlok" spelled as "Grinklok"

![Login-Picture](https://user-images.githubusercontent.com/16038306/32609705-d4c1003c-c560-11e7-8338-44a6302edf53.png)

**Comment by asdfjackal** [comment]
Zenith already exists in the current list under the "primaries" tab. If you are not seeing it please post a screenshot so that I can further diagnose the problem.

I have confirmed both the missing "Sigma and Octantis" as well as the spelling error in Grinlok. I will try to get those fixed in the next few days.

Progress Tracker:
- [ ] Add [Sigma and Octantis](http://warframe.wikia.com/wiki/Sigma_%26_Octantis)
- [ ] Rename Grinklok to Grinlok

**Comment by RylaiSlyfe** [comment]
I now checked again and you are right, the Zenith already exists
